# aws-load-balancer-controller-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::339712695628:role/eksctl-explore-california-dev-eks-addon-iamse-Role1-vIFDJX55RVKw

